### ISSUE TITLE
almost all links are broken

### ISSUE THREAD

**Issue by ghost** [astridx/boilerplate#16]
almost all links are broken  :(

**Comment by astridx** [comment]
What like do you mean exactly?

**Comment by astridx** [comment]
Oh, now I realize. You mean the links to the namespaced files that are now in the src folder. 
https://github.com/joomla/joomla-cms/pull/27687 will fix this later.

**Comment by LuizMarin** [comment]
Thanks for answering.
I know very little about Joomla. I am analyzing if I can migrate my applications to this platform. Your working model would be very valuable to me. But I confess that Joomla scares at its complexity. I appreciate any additional help.

**Comment by astridx** [comment]
Links are ok now
