### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by MarkRS-UK** [astridx/boilerplate#21]
Could I suggest not using "Joomla" as the company name in these examples.

Certainly for namespace beginners (like me) it makes it hard to know when to use "Joomla" and when "<company-name>".

**Comment by astridx** [comment]
Thanks, you are right. i change the company name to FooNamespace in the example files.

**Comment by fkolberg** [comment]
Comments and installable zip-files are not updated in this sense, there is joomla instead of FooNamespace.

**Comment by astridx** [comment]
Where exactly do you mean?

**Comment by fkolberg** [comment]
In boilerplate/tutorial/component/1-die-erste-ansicht-im-backend/com_foos.zip all contained files refer to Joomla/... - Namespace;

**Comment by astridx** [comment]
Oh, OK. Thank you, but I do not update the files in the tutorial directory. Anyone can do it themselves. Under releases there is a zip of the last version.

**Comment by fkolberg** [comment]
I tried to replace the namespace in all files of the com_foos.zip to FooNamespace\\...; 
and installed it again, succesfully;
but when clicking on COM_FOOS in the Administartor-Menu an error occurs: 
Invalid controller class: display 

in log-File:
2022-07-25T12:52:21+00:00	CRITICAL 127.0.0.1	error	Uncaught Throwable of type InvalidArgumentException thrown with message "Invalid controller class: display". Stack trace: #0 [ROOT]/libraries/src/Dispatcher/ComponentDispatcher.php(145): Joomla\CMS\Dispatcher\ComponentDispatcher->getController()
#1 [ROOT]/libraries/src/Component/ComponentHelper.php(389): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
...

Before that, I also tried to copy the code examples as described in your book an got the same error. 
In the Code-Examples  the company name was changed to FooNamespace, but I think there is still a problem. 

I'm new to Joomla, and cannot find what's going wrong in this case.

But I will thank you for your inspiring books and work on joomla and leaflet !!!

**Comment by fkolberg** [comment]
perhaps the problem is in provider.php: 

'\\NamespaceJoomla\\Component\\Foos' seems to be wrong

'\\FooNamespace\\Component\\Foos'  works fine :-)))
