### ISSUE TITLE
Switch categories when using Custom fields

### ISSUE THREAD

**Issue by Joomill** [astridx/boilerplate#25]
Hi Astrid,

Thanks for this Extension Development Tutorial. It is very helpful

I created a custom field and fieldgroup.
I also created another category.
When i switch category, it don't work.

![2021-08-01_22-18-11](https://user-images.githubusercontent.com/1471185/127784278-a0ec1c4b-c0a7-45de-955f-fa54cb078bd1.gif)

Changing field-type "categoryedit" to "category" works, but then the custom fields attached to a specific category don't show automatically so it's not an ideal solution.

I can't find the difference with com_content or com_contact.
Do you know how to fix/debug this?

**Comment by astridx** [comment]
Thank you very much for your comment. I will take a closer look. I'm not sure I'll get around to it this week. But next week for sure.

**Comment by Joomill** [comment]
Hi Astrid,

I think i found the solution for this bug.
I changed the FooModel.php (function loadFormData()) to:

`	/**
	 * Method to get the data that should be injected in the form.
	 *
	 * @return  mixed  The data for the form.
	 *
	 * @since   __BUMP_VERSION__
	 */
	protected function loadFormData()
	{
        $app = Factory::getApplication();

        // Check the session for previously entered form data.
        $data = $app->getUserState('com_foos.edit.foo.data', array());

        if (empty($data))
        {
            $data = $this->getItem();

            // Prime some default values.
            if ($this->getState('foo.id') == 0)
            {
                $data->set('catid', $app->input->get('catid', $app->getUserState('com_foos.foos.filter.category_id'), 'int'));
            }
        }

        $this->preprocessData('com_foos.foo', $data);

        return $data;
	}`

**Comment by astridx** [comment]
Yes, thank you very much @Joomill . I have integrated it in all branches up from t14a (Custom Fields). 

I have also integrated the Custom Fields in the left Joomla navigation now. The submenu no longer worked in com_fields.
