### ISSUE TITLE
Empty publishing dates

### ISSUE THREAD

**Issue by Joomill** [astridx/boilerplate#26]
You can set start and end publishing dates.
You can also change them to another date.
But when you empty the fields this publishing dates keep coming back.
see:
https://user-images.githubusercontent.com/1471185/127914407-a7c80869-af9c-42ea-87b5-26ae89ba2682.mp4

So it seems this code don't work well (FooTable.php), while it's the same as in com_content

```
if (!$this->publish_down) {
	$this->publish_down = null;
}

if (!$this->checked_out_time) {
	$this->publish_down = null;
}
```
When i change "null" to "0000-00-00 00:00:00" it works again but that's not the Joomla 4 style so i would like to avoid this.

The checked_out_time  is also saved as "0000-00-00 00:00:00" when empty, so it could be the same sort of 'problem'.

I will report a solution when i found one :)

**Comment by astridx** [comment]
Fixed here: https://github.com/astridx/boilerplate/commit/95b83b7f1cf2cbcba3b95271b7b7e302609a42b5

**Comment by astridx** [comment]
I will add this text to the[ tutorial text ](https://blog.astrid-guenther.de/en/joomla-ver%C3%B6effentlichen-und-erstecken)

> We need `store($updateNulls = true)` because the parent class `Table` sets the variable `$updateNulls` to `false`. This causes form fields that hold the value `null` not to be changed in the database. Most of the time this is correct. The most common case is probably that a value is not set from the beginning and has not been changed in the form when editing the element. Because an empty date field is stored in the database with `null`, it is necessary in our case to force the storage of `null` values. This is done by setting the variable `$updateNulls` to `true`.

Thank you @Joomill  for finding this issue.
