### ISSUE TITLE
Project Issue

### ISSUE THREAD

**Issue by carterterryw** [astridx/boilerplate#36]
I have been working through the tutorial and I can't get the select foo button to work in the backend menu. I have downloaded the completed tutorial and installed it on my site and it seems that the same issue persists there. What do you think I am missing here?

**Comment by astridx** [comment]
In which branch an on what view do you have the problem exactly?

**Comment by carterterryw** [comment]
I just downloaded the latest version from the release tab as well, I am experiencing the same issues. When selecting single foo as a menu item, the button to choose a foo does nothing when clicked. I went through the code and I am not seeing what is causing the issue. Nothing is being output to console and no javascript errors are being fired so far as I can see.

**Comment by astridx** [comment]
> I just downloaded the latest version from the release tab as well, I am experiencing the same issues. When selecting single foo as a menu item, the button to choose a foo does nothing when clicked. I went through the code and I am not seeing what is causing the issue. Nothing is being output to console and no javascript errors are being fired so far as I can see.

The version in the release tab is not current. The code in the branches is up to date.

Make sure that you use the correct names. If nothing happens  when you select a single Foo, it is usually due to a typing error. Background: JavaScript is being executed. You add this script in two places. First, you create the function `jSelectFoo_...` using variables.

```
...if (!isset($scriptSelect[$this->id])) {	$wa->addInlineScript("	window.jSelectFoo_" . $this->id . " = function (id, title, object) {		window.processModalSelect('Foo', '" . $this->id . "', id, title, '', object);	}",		[],		['type' => 'module']	);	$scriptSelect[$this->id] = true;}...
```

In the source code of the Joomla administration area, the following code is added:

```
<script nonce="sampleId=">function jSelectFoos_jform_request_id(id, title, object) { window.processModalSelect('Foo', 'jform_request_id', id, title, '', object);}</script>
```

A little later, you call the function.

```
...$urlSelect = $linkFoos . '&amp;function=jSelectFoo_' . $this->id;...
```

The name of the function must be the same in both places!

**Comment by astridx** [comment]
> I am in the tutorials branch. t5 never actually created the table for foos. I manually created it so I could move through the tutorial. t7 I believe is where the button to choose a foo in a menu item was introduced and it was not working for me.

I have just tested this. with me the database was created. Did you get an error message?

**Comment by carterterryw** [comment]
When I uploaded the file from the tutorials it gave me no errors, it just didn't create the database table. Also I copied and pasted the code from the tutorial so wouldn't the function names have been the same there? I guess that may be what is confusing me. I'm not 100% familiar with github, can you send me the link to the page with the up to date release?

**Comment by carterterryw** [comment]
Those scripts are created in the FooModal.php file right?

**Comment by astridx** [comment]
Please have a look here: https://blog.astrid-guenther.de/en/die-daten-der-datenbank-im-frontend-nutzen/
I have updated the text. On my blog you will always find the latest version

**Comment by astridx** [comment]
> I'm not 100% familiar with github, can you send me the link to the page with the up to date release?

I created a package for component, module and plugin here:https://github.com/astridx/boilerplate/releases/tag/v2.0.0

**Comment by astridx** [comment]
>  Also I copied and pasted the code from the tutorial so wouldn't the function names have been the same there?

The texts in the book should always match each other. They can differ from the code on github. This I update when something changes in joomla, or if I find an improvement. In your case, I found something here that may have led to problems. I am sorry for that: In an early sample code version for the field 'FooField' I do not use the Webasset Manager. The necessary changes can be found [here].

(Currently modifying the template for using the child function. )

**Comment by carterterryw** [comment]
Astrid, you are amazing. The 2.0 version of the package is working for me now. Thank you so much for you hard work. I can't wait to go back through the tutorial now with these files.
