### ISSUE TITLE
Links into the void 

### ISSUE THREAD

**Issue by ThomasFinnern** [astridx/boilerplate#4]
Hallo Astrid,
going through the wiki i stumbled over some links not matching wiki pages

* home 
* 000:  Developing a Basic Component
* 001:  next chapter
...

It looks like the three numbers up front have to be updated in the links

And i want to tell you that i appreciate your work very much

Regards Thomas

**Comment by astridx** [comment]
Oops, I renamed the menu items and then didn't correct all the links. Now it should fit. Thank you very much for your hint.
